### ISSUE TITLE
Seems failed to override forward()

### ISSUE THREAD

**Issue by songyuzhou324** [rosinality/adaptive-softmax-pytorch#1]
I got error as follows:

File "text8.py", line 121, in 
train()
File "text8.py", line 78, in train
loss = criterion(output, Y_var)
File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in call
result = self.forward(*input, **kwargs)
File "/AdaptiveSoftmaxPyTorch/adasoft.py", line 114, in forward
output += self.criterion(input[i], Variable(target[i]))
File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in call
result = self.forward(*input, **kwargs)
File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 71, in forward
raise NotImplementedError
NotImplementedError

Any idea?

**Comment by xiangzhumeng16** [comment]
0it [00:00, ?it/s]Traceback (most recent call last):
  File "text8.py", line 121, in <module>
    train()
  File "text8.py", line 75, in train
    hidden = repackage_hidden(hidden)
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor

as runing text8.py, the debug information above is present.

**Comment by rosinality** [comment]
Updated to newer version of PyTorch. (2f02ca68d34f83867bea385c4be23a5392823f1e) This will resolved the issue.
